### ISSUE TITLE
bmp680?

### ISSUE THREAD

**Issue by ReneSch** [IU5HKU/MiniWXStation#1]
Hi there!
i really like your weather station, but now i´m wondering is it possible to use a bmp680 instead of the bme280?

Best wishes!

**Comment by IU5HKU** [comment]
Thank you, and sorry for this very late reply, i haven't such a sensor in my hands, so i can't assure that my code works with bme680. I've searched around but i haven't found a seller, if you told me when i can buy a pair of them (if the price isn't too high!) i'll write a new code for this useful sensor.

**Comment by ReneSch** [comment]
Hi,
thank you very much for the answer!

i havent found a seller in italy but i´m willing to supply a sensor to you.

just get in touch with me and write me your adress (rene.schaepers@gmail.com)

best wishes!

**Comment by IU5HKU** [comment]
Just sent you an email, thank you Rene
