### ISSUE TITLE
Webconfig can't access

### ISSUE THREAD

**Issue by Muftiku21** [IU5HKU/MiniWXStation#13]
Hello master, I have some problem with my miniaprswx station
I'm using v1.1f
1. Can't open webconfig
![image](https://github.com/IU5HKU/MiniWXStation/assets/94301312/42cc659a-ce83-4b77-b96e-9ae7ee6e1ac8)

2. Can't set static ip
 this is my static ip settings, but my ip still in 192.168.1.11
![image](https://github.com/IU5HKU/MiniWXStation/assets/94301312/f86287c7-0a14-4343-bb13-65586f85970f)

This is my first time using arduino. 
Thank for help me.

**Comment by sq2mo** [comment]
This may be due to a NTP forever loop. You can check my fork, where the issue has been fixed.

**Comment by Muftiku21** [comment]
> This may be due to a NTP forever loop. You can check my fork, where the issue has been fixed.

![image](https://github.com/IU5HKU/MiniWXStation/assets/94301312/3c76172b-2cb6-4e95-97a6-1e64f45ead37)

Thankyou so much master
