### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dl9sec** [IU5HKU/MiniWXStation#16]
Hi Marco,

this is a really great project, which worked out of the box for me on a D1mini.
For users and contributors it would be great if the project gets a license (maybe an open source license).

Thank you.

73, Thorsten

**Comment by IU5HKU** [comment]
Sorry Thorsten, i've read your request just now...sure, il put an open source license in the next days, feel free to use and abuse this code in whatever way you want :-)
Have a nice day
 Marco

**Comment by IU5HKU** [comment]
Added GPL v3 license as requested, thanks for your hint
