### ISSUE TITLE
change line 827 in MiniWX_v1.0.ino

### ISSUE THREAD

**Issue by iw5ejm** [IU5HKU/MiniWXStation#2]
https://github.com/IU5HKU/MiniWXStation/blob/37946b18b47945d90adefb712e38ab3489cf30d5/V1.0/MiniWX_v1.0.ino#L827

change this line to:

`      message += FPSTR(HTTP_SCRIPT);
`

or there will be a compile error

73's!

**Comment by IU5HKU** [comment]
I've fixed the typo, thank you Marco
