### ISSUE TITLE
^:WARNING:^ no settings config found, write defaults settings.txt file open failed

### ISSUE THREAD

**Issue by ea8cwb** [IU5HKU/MiniWXStation#3]
I connect with monitor serial and make the config. It seems to be working good but... when i press exit i read this warning: ^:WARNING:^ no settings config found, write defaults settings.txt file open failed
So when i disconnect the module from my pc and try to connect it to a wall charger to fix the weather station on its place does not work.

Could you tell me what a i am doing wrong pleas? Did you have this problem any time?

**Comment by IU5HKU** [comment]
Sorry for the late reply, i think you forgot to flash correctly the SPIFFS part of the chip, and/or format it through the serial console menu. Let me know...
