### ISSUE TITLE
I can't compile because of an error

### ISSUE THREAD

**Issue by OM8AKX** [IU5HKU/MiniWXStation#4]
C:\Users\eMBe\Desktop\MiniWXStation-master\V1.1f\MiniWX_v1.1f\MiniWX_v1.1f.ino: In function 'void Send2Wunder()':

MiniWX_v1.1f:325:42: error: invalid conversion from 'const __FlashStringHelper*' to 'uint32_t {aka unsigned int}' [-fpermissive]

   if (!client.connect(FPSTR(WGserver), 80)) {

                                          ^

In file included from C:\Users\eMBe\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:31:0,

                 from C:\Users\eMBe\Desktop\MiniWXStation-master\V1.1f\MiniWX_v1.1f\MiniWX_v1.1f.ino:39:

C:\Users\eMBe\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/IPAddress.h:48:9: error:   initializing argument 1 of 'IPAddress::IPAddress(uint32_t)' [-fpermissive]

         IPAddress(uint32_t address);

         ^

exit status 1
invalid conversion from 'const __FlashStringHelper*' to 'uint32_t {aka unsigned int}' [-fpermissive]

**Comment by ha5dzs** [comment]
I had similar issues with the webserver, I was using the 2.6.2 version of the ESP board support package. I downgraded to 2.5.2 and everything works. Not sure why this happens, but thought it might help you.

**Comment by OM8AKX** [comment]
Solved. Using the older module helped. Thank you Zoli for the idea.
