### ISSUE TITLE
change a const name

### ISSUE THREAD

**Issue by iw5ejm** [IU5HKU/MiniWXStation#7]
https://github.com/IU5HKU/MiniWXStation/blob/ad4df6ba5a4a9644840a4d7f0a2b9dcd8ebbcc12/V1.1f/SystemWebpages.h#L43

change HTTP_HEAD_HTML to HTTP_HEAD or it will not compile :)

73's!!

**Comment by IU5HKU** [comment]
Sorry, the code is old, and in the meantime the sdk has changed...in the beginning this 'const' was unused by the esp8266 sdk...the proper version of the sdk is written in the beginning of the ".ino" files, for every version, please use that sdk to compile.
I've no spare time at moment to refactor the code, sorry.
Have a nice day.
